version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    volumes:
      - /etc/loki:/etc/loki
      - ./loki-data:/data/loki
    command: -config.file=/etc/loki/loki-config-300.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - /var/log:/var/log
      - /etc/promtail:/etc/promtail
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
        #- /tmp:/tmp
      - /var/lib/docker/containers:/var/lib/docker/containers:ro 
    command: -config.file=/etc/promtail/promtail-config-300.yaml
    networks:
      - loki

        #  grafana:
        #    image: grafana/grafana:latest
        #    ports:
        #      - "3000:3000"
        #    environment:
        #      - GF_SECURITY_ADMIN_USER=admin            # Default admin username
        #      - GF_SECURITY_ADMIN_PASSWORD=3&f7dVYq#j79 # Set new admin password
        #      - GF_SERVER_ROOT_URL=http://localhost     # Set the root URL (optional)
        #    volumes:
        #      - grafana-storage:/var/lib/grafana
        #    networks:
        #      - loki

volumes:
  #  grafana-storage:
  #    driver: local
  loki-data:
    driver: local
