server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.1.0.10:3100/loki/api/v1/push
    external_labels:
      host: docker

        #scrape_configs:

        #- job_name: container
        #docker_sd_configs:
        #- host: unix:///var/run/docker.sock
        #refresh_interval: 5s
        #relabel_configs:
        #- source_labels: ['__meta_docker_container_name']
        #regex: '/(.*)'
        #target_label: 'container'
        #
        #
scrape_configs:
  - job_name: container
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
